In [14]:
import cv2
import numpy as np 

In [12]:
#read image
image = cv2.imread('C:/Users/bigya/OneDrive/Desktop/opencv/traffic.jpg')
print(image.shape)
print(type(image))
print(image)


(1070, 2048, 3)
<class 'numpy.ndarray'>
[[[135 103  92]
  [141 106  96]
  [140  99  90]
  ...
  [ 97 110 118]
  [ 92 109 106]
  [114 135 127]]

 [[143 111 100]
  [146 111 101]
  [140 101  92]
  ...
  [ 73  87  93]
  [109 127 126]
  [129 152 144]]

 [[135 105  94]
  [140 108  97]
  [137 101  91]
  ...
  [ 47  66  71]
  [ 95 117 115]
  [ 89 112 107]]

 ...

 [[ 68  71  62]
  [ 68  71  62]
  [ 73  76  67]
  ...
  [ 64  57  42]
  [ 62  54  41]
  [ 69  62  47]]

 [[ 76  79  70]
  [ 75  78  69]
  [ 77  80  71]
  ...
  [ 62  54  37]
  [ 46  37  23]
  [ 49  41  24]]

 [[ 79  82  73]
  [ 78  81  72]
  [ 80  83  74]
  ...
  [140 132 115]
  [117 109  92]
  [124 116  99]]]


In [5]:
# convert into grayscale
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)


In [7]:
#Resize
print(image.shape)
image_resize = cv2.resize(image, (512, 512))
print(image_resize.shape)
image_resize = cv2.resize(image, (image.shape[0]//2, image.shape[1]//2)) #resize to half


(1070, 2048, 3)
(512, 512, 3)


In [ ]:
#flipping
image_flip = cv2.flip(image, 3)  #horizontal flip (any positive value)
image_flip = cv2.flip(image, 0) #vertical flip
image_flip = cv2.flip(image, -1) # both horizontal and vertical flip



In [11]:

#cropping
imageCrop = image[0:250, 0: 250]

# saving an image
cv2.imwrite('image/cropimage.png', imageCrop)

False

In [13]:
#  drawing shapes
cv2.rectangle(image, (50, 50), (500, 500), thickness = 2, color = (0, 0, 255))
cv2.circle(image, (image.shape[1] //2, image.shape[0]//2), radius = 100, color = (0, 255, 255), thickness = 4) # draw circle at centre
cv2.putText(image, f'text in image', fontScale= 3, color = (255, 50 , 50 ), org = (image.shape[1]//2, 100), fontFace = cv2.FONT_ITALIC, thickness= 5)


array([[[135, 103,  92],
        [141, 106,  96],
        [140,  99,  90],
        ...,
        [ 97, 110, 118],
        [ 92, 109, 106],
        [114, 135, 127]],

       [[143, 111, 100],
        [146, 111, 101],
        [140, 101,  92],
        ...,
        [ 73,  87,  93],
        [109, 127, 126],
        [129, 152, 144]],

       [[135, 105,  94],
        [140, 108,  97],
        [137, 101,  91],
        ...,
        [ 47,  66,  71],
        [ 95, 117, 115],
        [ 89, 112, 107]],

       ...,

       [[ 68,  71,  62],
        [ 68,  71,  62],
        [ 73,  76,  67],
        ...,
        [ 64,  57,  42],
        [ 62,  54,  41],
        [ 69,  62,  47]],

       [[ 76,  79,  70],
        [ 75,  78,  69],
        [ 77,  80,  71],
        ...,
        [ 62,  54,  37],
        [ 46,  37,  23],
        [ 49,  41,  24]],

       [[ 79,  82,  73],
        [ 78,  81,  72],
        [ 80,  83,  74],
        ...,
        [140, 132, 115],
        [117, 109,  92],
        [124, 116,  99]]

In [ ]:
# create own image
image = np.zeros((512, 512))

# close window on pressing 'X'
while True:
    cv2.imshow('window', image)
    if cv2.waitKey(1) & 0xFF == ord('X'):
        break

cv2.destroyAllWindows()


In [ ]:
#assign function to mouse operation
def draw(event, x, y, flags, params):
    if event == 1:
        # cv2.rectangle(image, (50, 50), (500, 500), thickness=2, color=(0, 0, 255))
        cv2.circle(image, center = (x, y), color = (255, 0,0), thickness = -1, radius = 10)

    if event == 4:
        print('mouse unclicked')

cv2.namedWindow('window')
cv2.setMouseCallback('window', draw)

while True:
    cv2.imshow('window', image)
    if cv2.waitKey(1) & 0xFF == ord('X'):
        break

cv2.destroyAllWindows()


In [ ]:
#draw rectangle in screen in real-time
flag = False
ix = -1
iy = -1

def draw(event, x, y, flag, params):
    global ix, iy
    if event == 1:
        flag = True
        ix = x
        iy = y

    if event == 0:
        if flag == True:
            cv2.rectangle(image, (ix,iy), (x, y), color = (255, 0,0), thickness = -1)

    if event == 4:
        flag = False
        cv2.rectangle(image, (ix, iy), (x, y), color = (255, 0,0), thickness = -1)



cv2.namedWindow('window')
cv2.setMouseCallback('window', draw)

while True:
    cv2.imshow('window', image)
    if cv2.waitKey(1) & 0xFF == ord('X'):
        break

cv2.destroyAllWindows()


In [ ]:
# crop image in real time
ix = -1
iy = -1
flag = False

def crop(event, x, y, flag, params):
    global ix, iy

    if event == 1:
        print('inside click')
        flag = True
        ix = x
        iy = y


    if event == 0:
        if flag == True:
            print('drag')

    if event == 4:
        flag = False
        fx = x
        fy = y
        # cv2.rectangle(image, (ix, iy), (x, y), color = (0, 0, 0), thickness = -1)
        imageCrop = image[iy:fy, ix:fx]
        cv2.imshow('new_window', imageCrop)
        cv2.waitKey(0)

cv2.namedWindow('window')
cv2.setMouseCallback('window', crop)
while True:
    cv2.imshow('window', image)
    if cv2.waitKey(1) & 0xFF == ord('X'):
        break

cv2.destroyAllWindows()


In [ ]:
# working with vidoes

# webcam
vid = cv2.VideoCapture(0)
while True:
    ret, frames = vid.read()
    print(ret)
    cv2.imshow('webcam', frames)
    if cv2.waitKey(1) & 0xFF == ord('X'):
        break

cv2.destroyAllWindows()

video
vid = cv2.VideoCapture('C:/Users/bigya/PycharmProjects/env312/pythonProject/video/bike.mp4')

while True:
    ret, frames = vid.read()
    cv2.imshow('videoClip', frames)
    if cv2.waitKey(1) & 0xFF == ord('X'):
        break

cv2.destroyAllWindows()